### ISSUE TITLE
feat: Analytics site (Mainnet & Arbitrum metrics)

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/v2-ui#1751]
## Summary

The general idea is to consolidate a wide single source of data in our site (i.e: `https://app.badger.com/analyticis` unless that architecture wise is better to have a completely different site), which will serve users and internal members to have a peak of the most relevant metrics around setts, emissions, harvest health, ops cost and treasury positions.

## Requirements

1. Treasury
    -  Visualize treasury holdings on each of the relevant msig (where is located, token, amount)
    -  Historical profit of the treasury, accrued and current claimable yield (expressed in dollar denomination)
    - Allow inspection per individual msig/contract, for granularity

2. Operations cost
    - Total ops cost breakdown in different time frames (1d, 1w, 1m)
    - Ops breakdown by: tree, harvest tx and msig cost.

3. Harvest performance. Similar info as [bounty site](https://badger-dao-analytics.herokuapp.com/)
    - Tx breakdown of asset sent to tree and msig (perf fee gov)
    - Allow csv generation of the table data (for specific timeframe explored). Weekly, monthly, quarterly and yearly
    - Gas spent per tx
    - Calc comparison between amount harvested vs gas cost
    - Contain information on both: dollar denomination and raw token amounts for references

4. Emissions schedules historical
    - Present schedules in table format, properly formatted units and dates. Content similar as [csv](https://docs.google.com/spreadsheets/d/1_QvMZQTR4un78rmgAub2-3pzL-OtuGktkNkO1aYI7f0/edit#gid=1357326547)
    - Expose total breakdown per sett & token in different timeframes (1w, 1m ,1q)
    - Allow downloading from UI the CSV table content for exploration

5. Sett tx history overview
    - Identify action type (deposit or withdraw)
    - Show amounts (also dollar value at the block height)
    - Anchor tag to tx hash, account and time (similar columns as tx in uniswap info site for [transaction section](https://info.uniswap.org/#/pools/0xe15e6583425700993bd08f51bf6e7b73cd5da91b)

## Documentation

General scope: https://docs.google.com/document/d/19SwDOtfWQ3GaMxF3A-Vin-ymIhn828PM9qugJEuM7W8/edit

Endpoint architecture: TBD

## Tasks

- [ ] Create endpoint architecture
- [ ] Validity of data and accuracy
- [ ] Mock-up designs 
- [ ] F/e integration with endpoints after design deliverables

**Comment by mrbasado** [comment]
closeing, @ICEBADGER can make a change request if we decide we want to do it
